In [1]:
import torch


In [4]:
a=torch.ones(5)

In [5]:
a

tensor([1., 1., 1., 1., 1.])

In [6]:
a[1]=2.0
a

tensor([1., 2., 1., 1., 1.])

In [7]:
#Creating tensor with 0
points=torch.zeros(6)
points

tensor([0., 0., 0., 0., 0., 0.])

In [9]:
points[1]=1.0
points[2]=2.0
points[3]=3.0
points[4]=4.0
points[5]=5.0
points[0]=3.0
points

tensor([3., 1., 2., 3., 4., 5.])

In [14]:
float(points[1]),float (points[4])

(1.0, 4.0)

In [16]:
points.shape

torch.Size([6])

In [17]:
#Create tensor with predefine shape 
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [18]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

Acessing tensor 

In [19]:
points[0, 1]

tensor(1.)

In [20]:
points[2, 1]

tensor(1.)

In [22]:
some_list = list(range(6))
some_list[:]

[0, 1, 2, 3, 4, 5]

In [23]:
some_list[1:4]

[1, 2, 3]

In [24]:
some_list[1:]


[1, 2, 3, 4, 5]

In [25]:
some_list[:4]


[0, 1, 2, 3]

In [26]:
some_list[:-1]


[0, 1, 2, 3, 4]

In [27]:
some_list[1:4:2]

[1, 3]

Named tensors

In [36]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]
weights = torch.tensor([0.2126, 0.7152, 0.0722])
img_t

tensor([[[-0.3982,  0.6803, -0.6684, -1.1933, -1.8306],
         [-0.1617,  0.5965, -1.2948,  0.0604,  0.7885],
         [-0.5911, -0.5506,  0.3423, -0.2250, -0.7396],
         [-0.5551,  1.5017,  0.4166,  0.3634, -0.5486],
         [ 0.6199, -1.7311,  0.0454,  0.6336, -0.6385]],

        [[ 1.1623, -1.0575,  0.4598,  2.2026,  1.2009],
         [-1.0490, -1.3834,  1.7208,  0.2106, -1.3646],
         [ 0.7187,  1.1127, -0.2823,  0.1494, -0.4399],
         [-0.4236,  0.8370,  0.3204,  1.1042, -1.7961],
         [ 1.6516,  0.4225,  0.2038, -1.4790,  0.0083]],

        [[ 1.0521,  0.7328, -0.0850,  0.0987, -0.9533],
         [-1.3627,  0.4278,  0.2168, -0.6823,  0.1398],
         [ 0.2998, -0.0838,  0.7816,  0.6571,  0.6424],
         [-1.5332, -0.1050, -1.6041,  0.4899, -2.2500],
         [-1.1209,  0.9421, -0.1568, -0.3256, -0.0629]]])

In [37]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]
batch_t

tensor([[[[-0.4201,  0.4800,  0.8944,  0.0832,  1.8767],
          [-1.4374, -0.5281, -1.0490, -0.5498, -1.8457],
          [ 0.1728,  0.6413,  1.3517,  2.3117, -0.4079],
          [-2.2345,  0.2157, -0.6212,  0.6150, -0.9566],
          [ 0.3622,  1.6547, -1.3489, -0.3850, -0.0443]],

         [[-0.6054, -1.4725,  1.1943, -0.6072, -0.7960],
          [-0.1490,  0.9209,  0.9105, -0.2601, -2.0527],
          [ 1.3756,  1.3283, -1.5880, -0.5992,  0.8013],
          [-0.9476, -0.3378, -0.4515,  0.2412, -0.0855],
          [ 1.3425, -0.6011,  0.5640,  0.0587,  0.2117]],

         [[ 0.5393,  0.1771, -0.9072,  0.2859, -0.0736],
          [-0.2251,  0.1938, -0.6311,  0.4203,  0.5437],
          [ 1.3949, -1.1504, -0.5260, -0.2237,  0.8509],
          [-0.7582, -0.9514, -3.0229, -0.9410,  1.0793],
          [-1.9510, -0.6041, -1.1601,  1.2552, -0.7456]]],


        [[[-2.2704,  0.2202, -1.0472, -0.0100,  0.1927],
          [-0.9774,  0.3950, -1.0239,  0.4068,  0.5492],
          [ 1.0735, -1.

In [38]:
img_gray_naive = img_t.mean(-3)
img_gray_naive

tensor([[ 0.6054,  0.1185, -0.0979,  0.3693, -0.5277],
        [-0.8578, -0.1197,  0.2143, -0.1371, -0.1454],
        [ 0.1425,  0.1594,  0.2805,  0.1938, -0.1791],
        [-0.8373,  0.7446, -0.2890,  0.6525, -1.5316],
        [ 0.3835, -0.1222,  0.0308, -0.3903, -0.2310]])

In [39]:
img_gray_naive = img_t.mean()
img_gray_naive

tensor(-0.0628)

In [40]:
img_gray_naive = img_t.mean(-2)
img_gray_naive

tensor([[-0.2172,  0.0993, -0.2318, -0.0722, -0.5938],
        [ 0.4120, -0.0138,  0.4845,  0.4375, -0.4783],
        [-0.5330,  0.3828, -0.1695,  0.0475, -0.4968]])

In [33]:
batch_gray_naive = batch_t.mean(-3)
batch_gray_naive

tensor([[[-0.1817,  0.0783, -0.1890, -0.5406,  0.2374],
         [-0.2001,  0.7336,  0.3456,  0.1863, -0.7563],
         [-0.4294, -0.5256, -0.9469, -0.2321,  0.3895],
         [-0.5930,  0.3926, -0.2949,  0.2414,  0.0287],
         [-0.6395,  0.4135,  0.2032, -1.3848,  0.3770]],

        [[-0.5020,  0.1503, -0.7597, -0.8051,  0.0642],
         [ 0.4012,  0.9667, -0.5613, -0.5901,  0.5687],
         [ 0.5061,  0.3599,  1.0513, -0.4424,  0.5113],
         [ 0.2298,  0.1202,  0.7847,  0.6604,  1.1331],
         [ 0.3862, -0.5985,  1.1520, -0.0155, -0.1612]]])

In [41]:
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([3, 5]), torch.Size([2, 5, 5]))

Managing a tensor’s dtype attribute

In [42]:
double_points = torch.ones(10, 2, dtype=torch.double)
double_points

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [43]:
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)
short_points

tensor([[1, 2],
        [3, 4]], dtype=torch.int16)

In [44]:
short_points.dtype

torch.int16

Tensor operations

In [46]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)
a_t

tensor([[1., 1., 1.],
        [1., 1., 1.]])

# Numpy to Torch and back

In [2]:
import numpy as np
x=np.random.rand(5,5)
x

array([[0.30874215, 0.59852078, 0.95184235, 0.19163296, 0.6686562 ],
       [0.03513675, 0.01994728, 0.16670191, 0.132075  , 0.3364248 ],
       [0.19568743, 0.84543262, 0.07012753, 0.0726222 , 0.13096798],
       [0.844013  , 0.51356337, 0.04756374, 0.67110241, 0.27020986],
       [0.58354245, 0.79105487, 0.54091374, 0.0461449 , 0.70550585]])

In [3]:
y=torch.from_numpy(x)
y

tensor([[0.3087, 0.5985, 0.9518, 0.1916, 0.6687],
        [0.0351, 0.0199, 0.1667, 0.1321, 0.3364],
        [0.1957, 0.8454, 0.0701, 0.0726, 0.1310],
        [0.8440, 0.5136, 0.0476, 0.6711, 0.2702],
        [0.5835, 0.7911, 0.5409, 0.0461, 0.7055]], dtype=torch.float64)

In [4]:
y.numpy()

array([[0.30874215, 0.59852078, 0.95184235, 0.19163296, 0.6686562 ],
       [0.03513675, 0.01994728, 0.16670191, 0.132075  , 0.3364248 ],
       [0.19568743, 0.84543262, 0.07012753, 0.0726222 , 0.13096798],
       [0.844013  , 0.51356337, 0.04756374, 0.67110241, 0.27020986],
       [0.58354245, 0.79105487, 0.54091374, 0.0461449 , 0.70550585]])

The memory is shared between the Numpy array and Torch tensor, so if you change the values in-place of one object, the other will change as well.

In [5]:
y.mul_(3)

tensor([[0.9262, 1.7956, 2.8555, 0.5749, 2.0060],
        [0.1054, 0.0598, 0.5001, 0.3962, 1.0093],
        [0.5871, 2.5363, 0.2104, 0.2179, 0.3929],
        [2.5320, 1.5407, 0.1427, 2.0133, 0.8106],
        [1.7506, 2.3732, 1.6227, 0.1384, 2.1165]], dtype=torch.float64)

In [6]:
x

array([[0.92622645, 1.79556234, 2.85552704, 0.57489888, 2.0059686 ],
       [0.10541025, 0.05984185, 0.50010572, 0.39622499, 1.0092744 ],
       [0.5870623 , 2.53629785, 0.2103826 , 0.21786661, 0.39290395],
       [2.53203901, 1.54069011, 0.14269123, 2.01330722, 0.81062957],
       [1.75062734, 2.37316462, 1.62274121, 0.13843471, 2.11651755]])